### ISSUE TITLE
Cmake failure on directory with forward slash ("\") in name

### ISSUE THREAD

**Issue by cgzr** [y-256/libdivsufsort#18]
System:
OS - Ubuntu 16.04 LTS

Steps to replicate this issue:
```
mkdir "dir\fail"
cd "dir\fail"
git clone https://github.com/y-256/libdivsufsort.git
cd libdivsufsort/
mkdir build
cd build
cmake ..
CMake Error: The source directory "/tmp/dir/fail/libdivsufsort" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by kloetzl** [comment]
Even though I can reproduce the error, it also happens with other cmake projects. Are you sure this is specific to libdivsufsort and not a quirks of cmake in general?

**Comment by cgzr** [comment]
No, I am not, could be a cmake issue. Feel free to close

**Comment by kloetzl** [comment]
I took another look and found a simpler case:

```
$ mkdir dir\\fail
$ cmake --open dir\\fail
Error: /tmp/dir/fail is not a directory
```

So this really is a cmake issue. For some reason it converts the `\` to a `/`. Unfortunately, I do not have the permissions to close this issue. Would you be so kind as to do that?

cmake has a separate [bug tracker](https://gitlab.kitware.com/cmake/cmake/issues). Do you want to file a new issue there?

Btw, thanks for reporting!

**Comment by cgzr** [comment]
Thank you, for your expertise and shared link (I was unable to find that cmake page during a brief search yesterday).
