### ISSUE TITLE
Linking issues on Mac

### ISSUE THREAD

**Issue by waitaria** [y-256/libdivsufsort#20]
Hi, I am trying to use this project on my MacBook, running MacOS version 10.15.1.

I have followed the build process from the README, where I:
1. Downloaded the zip file
2. Created the build directory, and entered into it.
3. Ran the command
`cmake -DCMAKE_BUILD_TYPE="Release" \
-DCMAKE_INSTALL_PREFIX="/usr/local" ..`
4. Compiled the package, by running 
`make'

Then, I copied the example code from the README:

    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    #include <divsufsort.h>

    int main() {
        // intput data
        char *Text = "abracadabra";
        int n = strlen(Text);
        int i, j;

        // allocate
        int *SA = (int *)malloc(n * sizeof(int));

        // sort
        divsufsort((unsigned char *)Text, SA, n);

        // output
        for(i = 0; i < n; ++i) {
            printf("SA[%2d] = %2d: ", i, SA[i]);
            for(j = SA[i]; j < n; ++j) {
                printf("%c", Text[j]);
            }
            printf("$\n");
        }

       // deallocate
       free(SA);

       return 0;
    }

And I put this code into a file named _test.c_. This file was placed in the ibdivsufsort-master directory. I then ran 

`gcc -v -o test test.c`

to compile the test program, but the compilation failed, producing this output:

`Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=10.15 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -Wno-framework-include-private-from-public -Wno-atimport-in-framework-header -Wno-extra-semi-stmt -Wno-quoted-include-in-framework-header -fdebug-compilation-dir /Users/danielroodt/Downloads/libdivsufsort-master -ferror-limit 19 -fmessage-length 181 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/y8/j4wn_10135d2lhdssc33jqq40000gq/T/test-c97c70.o -x c test.c
clang -cc1 version 11.0.0 (clang-1100.0.33.8) default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o test /var/folders/y8/j4wn_10135d2lhdssc33jqq40000gq/T/test-c97c70.o -L/usr/local/lib -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_divsufsort", referenced from:
      _main in test-c97c70.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Would you please be able to help me with how to build and use this API? 

Thanks a lot for your help.

**Comment by kloetzl** [comment]
As you want to use *lib*divsufsort, you have to link against the library. Try `gcc -v -o test test.c -ldivsufsort`.

**Comment by waitaria** [comment]
Ok, that works now, thanks a lot!

**Comment by dhowe** [comment]
Having a similar issue here, @kloetzl 

When I run `$ gcc -o test test.c -ldivsufsort .` after running `sudo make install`,  
I get the following:
```
test.c:5:10: fatal error: divsufsort.h: No such file or directory
    5 | #include <divsufsort.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

When I run `gcc -I/usr/local/include  -o test test.c -ldivsufsort .`
I get:
```
ld: library 'divsufsort' not found
collect2: error: ld returned 1 exit status
```
Same if I set LD_LIBRARY_PATH

thanks!

**Comment by kloetzl** [comment]
> after running `sudo make install`.

Did that give any errors? Where did the library get installed?

**Comment by dhowe** [comment]
No errors:
```
$ ls -l /usr/local/lib/libdivsufsort.*
-rwxr-xr-x  1 root  admin  - 67720 Jul 18 11:28 /usr/local/lib/libdivsufsort.3.0.1.dylib
lrwxr-xr-x  1 root  admin  -    25 Jul 18 11:28 /usr/local/lib/libdivsufsort.3.dylib -> libdivsufsort.3.0.1.dylib
lrwxr-xr-x  1 root  admin  -    21 Jul 18 11:28 /usr/local/lib/libdivsufsort.dylib -> libdivsufsort.3.dylib

$ ls -l /usr/local/include/divsufsort.h 
-rw-r--r--  1 root  admin  - 5442 Jul 18 11:23 /usr/local/include/divsufsort.h
```

**Comment by kloetzl** [comment]
That does look good. Note that on mac you will have to use `DYLD_LIBRARY_PATH` to set the path.

**Comment by dhowe** [comment]
For others, this is what eventually worked:
$ gcc -o test test.c -ldivsufsort -I/usr/local/include -L /usr/local/lib
