### ISSUE TITLE
broken PROJECT_VERSION_FULL

### ISSUE THREAD

**Issue by kloetzl** [y-256/libdivsufsort#5]
Trying to build libdivsufsort fails early in the make process. The error is in the `config.h`:

```C
/** Define to the version of this package. **/
#define PROJECT_VERSION_FULL "2.0.1-11-g735637c
"
```

So somehow an extra newline is added there. Deleting that fixes the problem. Unfortunately, I don't speak cmake, so I don't know how to fix that. :wink: 

Cheers
Fabian Klötzl

**Comment by kloetzl** [comment]
Fixed in pull request #7.

**Comment by simongog** [comment]
I have the same issue. Are you planning to merge @kloetzl solution soon? Thanks.

**Comment by kloetzl** [comment]
For the record: libdivsufsort now has a Debian [package](https://tracker.debian.org/pkg/libdivsufsort). That avoids this issue and has improved multi-arch support with patches from @thinred.

**Comment by xpflow** [comment]
The patch referred by @kloetzl is here btw: https://sources.debian.net/src/libdivsufsort/2.0.1-2/debian/patches/0001-Fix-upstream-cmake-files-to-support-multi-arch.patch/

**Comment by simongog** [comment]
Thanks for pointing this out @kloetzl and @xpflow .
